### ISSUE TITLE
Goals for the week (21.10-27.10)

### ISSUE THREAD

**Issue by cinnmnm** [TeaWhoYou/SeekFit#1]
# Goals to Accomplish This Week

We need to:

- [x]  **Make one use case diagram per person (and some sequence diagrams)**. As we discussed on Monday, everybody will prepare a diagram tied to one of the following views (example use cases in brackets):
  - [x]  **Wardrobe** (editing items or searching items)
  - [x] **Camera** (adding items)
  - [x] **Calendar** (adding planned outfits to dates)
  - [x] **Social Feed** (adding a friend / sending friend request)
  - [x] **Profile** (loggin in or changing some information about profile)

  Please declare what you will be doing, so we have everything covered. It would be best to post a textual description of the use case before making the diagram. (One of the tools for making diagrams: [https://app.diagrams.net/](https://app.diagrams.net/))

- [x] **Current [functional requirements](https://github.com/TeaWhoYou/SeekFit/wiki/Functional-Requirements)** need to be defined more precisely. Please look through the ones that concern your topic and split them into simpler ones based on the rule "Can I easily test it?".

- [x] **Fill in [non-functional requirements](https://github.com/TeaWhoYou/SeekFit/wiki/Non%E2%80%90functional-Requirements)**.
- [x] **Agree on [technologies](https://github.com/TeaWhoYou/SeekFit?tab=readme-ov-file#technologies) to be used**.

**Comment by cinnmnm** [comment]
I will prepare a use case diagram related to adding new items (garments/outfits).

**Comment by gienon-fer** [comment]
I'll do a use case diagram regarding friend groups.

**Comment by TiaRapo** [comment]
I'll cover the one related to editing/searching items.

**Comment by tiapl** [comment]
I'll cover the one related to editing/searching items.

**Comment by Cristrotar** [comment]
I can do then either the calendar or the Profile.

**Comment by gienon-fer** [comment]
> I can do then either the calendar or the Profile.

Please decide and proceeed

@Cristrotar if you choose the profile, please do login part, as we need it for the first version

**Comment by Cristrotar** [comment]
I'll do the calendar then( adding planned outfits)

**Comment by BartulK** [comment]
I will do the profile part

**Comment by bartulkajmak** [comment]
I will do the profile part
