### ISSUE TITLE
Goals for the week (28.10.-3.11.)

### ISSUE THREAD

**Issue by tiapl** [TeaWhoYou/SeekFit#2]
# Goals to Accomplish This Week

- [ ] **Make new, or rework current use case diagrams.** Each of the following topics should have one diagram:
  - [x] System (main features)
  - [x] Profile management (log in, personal information)
  - [x] Item management (individual pieces and outfits, adding, removing, editing)
  - [ ] Friend list management (sending, accepting and ignoring requests)
  - [x] Group management (creating groups and invitations, joining, exiting)
  - [x] Scheduling outfits (calendar, weather recommendations)

- [ ] **Make new, or rework current sequence diagrams.** Each of the following topics should have one of its functionalities described by the diagram:
  - [x] Profile management
  - [x] Item management
  - [ ] Friend list management
  - [x] Group management
  - [x] Scheduling outfits

- [x] **Organize the Wiki page.** The diagrams should be uploaded in a logical order, and have matching names and formats.

Please declare which topic you will make diagrams for. As previously mentioned, recommended tool for this task is: [https://app.diagrams.net/](https://app.diagrams.net/)

**Comment by tiapl** [comment]
I will cover the item management topic.

**Comment by cinnmnm** [comment]
I can try to do the system diagram.

**Comment by cinnmnm** [comment]
I'll rework the join group sequence diagram.

**Comment by Cristrotar** [comment]
I'll do the use cases and sequence diagrams for scheduling outfits

**Comment by BartulK** [comment]
I will do profile management use case and sequence diagrams

**Comment by bartulkajmak** [comment]
I will do profile management use case and sequence diagrams

**Comment by tiapl** [comment]
I will also make a use case diagram for group management.
