### ISSUE TITLE
Goals for the week (4.11.-10.11.)

### ISSUE THREAD

**Issue by tiapl** [TeaWhoYou/SeekFit#3]
- [ ] Make new, or rework current use case diagrams for following topics:
  - [ ] System
  - [x] Profile management
  - [ ] Item management
  - [x] Friend list management
  - [ ] Group management
  - [x] Scheduling outfits

- [ ] Make new, or rework current sequence diagrams related to following topics:
  - [x] Profile management
  - [ ] Item management
  - [x] Friend list management
  - [ ] Group management
  - [x] Scheduling outfits

- [x] Make use case specifications for each use case displayed in use case diagrams covering following topics:
  - [x] Profile management
  - [x] Item management
  - [x] Friend list management
  - [x] Group management
  - [x] Scheduling outfits

- [x] Organize the Wiki page.

Please declare which topic you will cover.

**Comment by bartulkajmak** [comment]
I will cover tasks related to profile management

**Comment by KyryloRotan** [comment]
I will create use case specifications for group management

**Comment by Cristrotar** [comment]
I'll cover all tasks related to scheduling outfits

**Comment by cinnmnm** [comment]
I can create use case specifications for item management based on the current use case diagram. I will also work coding the front end of the Wardrobe view.

**Comment by tiapl** [comment]
I'll do the friend list management

**Comment by gienon-fer** [comment]
I've just created the required wiki page for system architecture. We still need to have the use case diagrams updated/created.
