### ISSUE TITLE
Review and Refine Project Feature Descriptions for Enhanced Functionalities

### ISSUE THREAD

**Issue by VladoSruk** [TeaWhoYou/SeekFit#5]
During the function analysis phase, several features specified in the requirements were identified as enhancements beyond the core app functionalities. This issue aims to improve the project feature descriptions by clarifying core functionalities and highlighting additional features that serve as enhancements.
Suggested Action
•	Review: Revisit the list of features, distinguishing between essential functionalities and those that are considered enhancements.
•	Update Descriptions: Modify the project description and feature set to clearly indicate core features versus enhanced functionalities.
•	Documentation: Update relevant documentation or README files to ensure alignment and clarity in feature descriptions.
Acceptance Criteria
1.	All core and enhancement functionalities are clearly defined in the project feature descriptions.
2.	Updated documentation with a detailed description of core features and optional enhancements.
3.	Any further functional requirements are categorized appropriately.
Additional Notes
Enhancements may include features that improve user experience but are not necessary for the minimum viable product (MVP).

**Comment by tiapl** [comment]
I updated the project description in the Wiki with more detailed descriptions of app functionalities.

I am unsure if I should explicitly mention which of those functionalities are core or enhancement. A list like that doesn't seem to fit with the description on Wiki, so would it be alright to put the list of functionalities in the README description?

**Comment by cinnmnm** [comment]
I updated the README file. Now it includes a project description that mentions all features without going into much detail (we have the wiki page for that), and a section on core functional requirements.
