### ISSUE TITLE
Align Use Case Diagrams with Project Feature Descriptions and Functional Requirements

### ISSUE THREAD

**Issue by VladoSruk** [TeaWhoYou/SeekFit#7]
The use case diagrams contain several use cases that are not currently covered in the project’s functionalities or feature descriptions. This issue aims to align the diagrams with the existing feature set or update the feature descriptions to ensure clarity and consistency.
Suggested Action
1.	Review project descrition and FR: Reassess the use case diagrams to identify and document any uncovered functionalities that are potentially useful.
2.	Update Descriptions: Adjust the project feature descriptions to either incorporate the uncovered use cases as part of the project’s scope or document them as potential future enhancements.
3.	Enhance Documentation: Ensure that the project’s documentation reflects these updates and that there’s a clear alignment between diagrams and feature descriptions.
Acceptance Criteria
1.	Use case diagrams accurately reflect all core and enhancement functionalities described in the project documentation.
2.	Project feature descriptions are updated to address any newly included use cases or clearly mark them as potential future enhancements.
3.	Documentation is clear and provides a comprehensive overview of functionalities aligned with the use case diagrams.
Additional Notes
This enhancement will ensure that the project remains well-defined and that any additional use cases are either part of the core functionalities or documented as future development opportunities.

**Comment by tiapl** [comment]
I reviewed the project description and functional requirements, and compared them to the use case diagrams. I found inconsistencies with three diagrams:
- Scheduling outfits: missing use case specifications
- Group management: inconsistencies regarding interactions within the group
- Profile management: missing use cases regarding wish list management
