### ISSUE TITLE
Review Use Case Diagrams for Semantic Correctness of Relationships

### ISSUE THREAD

**Issue by VladoSruk** [TeaWhoYou/SeekFit#8]
There may be instances where the semantic relationships (extend, include, generalization) between use cases in the documentation are not accurately represented or are missing. This can lead to misunderstandings and inconsistencies in the system design.
Goals:
• Ensure Correct Usage of Relationships: Verify that extend, include, and generalization relationships are used appropriately.
• Identify Missing Relationships: Discover any missing relationships that could clarify the system's behavior.
• Improve Diagram Clarity: Enhance the readability and understanding of the use case diagrams.
• Add one more diagram eg. „User Interactions with Gym Recommendations Use Case Diagram“
Tasks:

Review All Use Case Diagrams: Examine each diagram to identify potential issues.
Check Extend Relationships:
o Ensure that extend relationships are used to represent optional behaviors.
o Verify that the base use case can be executed independently.
Check Include Relationships:
o Ensure that include relationships represent common behavior shared by multiple use cases.
o Verify that the included use case cannot be executed independently.
Check Generalization Relationships:
o Ensure that generalization relationships correctly represent a "specialization" or "sub-type" relationship between use cases.
o Verify that the specialized use case inherits all the behaviors of the generalized use case.
Acceptance Criteria:
• All use case diagrams are reviewed for semantic correctness.
• Any incorrect or missing relationships are corrected or added.
• The diagrams are updated to reflect the changes.
• Consistency: Ensure consistency in the use of relationships across all diagrams.
• Clarity: Use clear and concise notation to represent relationships.
•
By addressing these issues, we can improve the accuracy and clarity of the use case diagrams, leading to a better understanding of the system's requirements.

**Comment by tiapl** [comment]
I went through the diagrams and corrected mistakes. I also simplified some use cases and relationships to enhance readability.
